dingdingding.org
https://civic.mit.edu/
https://github.com/mitmedialab/gobo
https://flygirlsofcambridge.com/
http://networkcultures.org/
https://schoolofdata.org/
https://spectrum.chat/wip
https://explorabl.es/
https://www.youtube.com/watch?v=WhE2TUZXQQU
https://www.creativeapplications.net/
https://www.rand.org/
https://thenewstack.io/
https://lettier.github.io/posts.html
